<?php

/**
 * @file
 * Install for a basic entity - need to create the base table for our entity.
 * This table can have as many columns as you need to keep track of
 * entity-specific data that will not be added via attached fields.
 * The minimum information for the entity to work is an id and an entity name.
 */

/**
 * Implements hook_schema().
 *
 * @ingroup coupon
 */
function coupon_schema() {
    $schema = array();

    // The name of the table can be any name we choose. However, namespacing the
    // table with the module name is best practice.
    $schema['coupon'] = array(
        'description' => 'The base table for our basic entity.',
        'fields' => array(
            'id' => array(
                'description' => 'Primary key of the  coupon.',
                'type' => 'serial',
                'unsigned' => TRUE,
                'not null' => TRUE,
            ),
            'type' => array(
                'description' => 'Type',
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'coupon_code' => array(
                'description' => 'coupon code',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'created' => array(
                'description' => 'Created Date ',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'promo_startdate' => array(
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'promo_enddate' => array(
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'crusie_startdate' => array(
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'crusie_enddate' => array(
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'rate' => array(
                'description' => 'Coupon Rate',
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'coupontype' => array(
                'description' => 'Coupon Type',
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'couponactive' => array(
                'description' => 'Coupon Active or not.',
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'company' => array(
                'description' => 'Coupon Company',
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'comments' => array(
                'description' => 'Coupon Comments',
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'modified' => array(
                'description' => 'The Unix timestamp of the entity modified time.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'coupon_validatetype' => array(
                'description' => 'coupon validate Type(sequential or multi date range).',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'coupon_discounteddates' => array(
                'description' => 'coupon Discounted Dates.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'deal_name' => array(
                'description' => 'Deal name for Groupons.',
                'type' => 'varchar',
                'length' => 255,
//                'not null' => TRUE,
                'default' => '',
            ),
            'deal_desc' => array(
                'description' => 'Deal Description for Groupons.',
                'type' => 'text',
                'size' => 'big',
//                'not null' => TRUE
            ),
            'deal_sell_price' => array(
                'description' => 'Deal sell price for Groupons.',
                'type' => 'varchar',
                'length' => 255,
//                'not null' => TRUE,
                'default' => '',
            ),
            'deal_cruise_template' => array(
                'description' => 'Deal Cruise template for Groupons.',
                'type' => 'varchar',
                'length' => 255, 
//                'not null' => TRUE,
                'default' => '',
            ),
            
            'deal_cruise_tickets' => array(
                'description' => 'Deal Cruise template tickets for Groupons',
                'type' => 'varchar',
                'length' => 255,
//                'not null' => TRUE,
                'default' => '',
            ),
            'used' => array(
                'description' => 'coupon used or not.',
                'type' => 'varchar',
                'length' => 255,
//                'not null' => TRUE,
                'default' => '',
            ),
        ),
        'primary key' => array('id'),
    );



    $schema['coupon_event'] = array(
        'description' => 'coupon and Events related table',
        'fields' => array(
            'id' => array(
                'description' => t('Primary ID'),
                'type' => 'serial',
                'not null' => TRUE
            ),
            'coupon_id' => array(
                'description' => 'coupon Id',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'Event_id' => array(
                'type' => 'text',
                'size' => 'big',
                'not null' => TRUE
            ),
            
            'coupon_eventtype' => array(
                'description' => 'coupon Event Type(Either All or Individual coupons).',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'created' => array(
                'description' => 'created',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
        ),
        'primary key' => array('id'),
    );
    $schema['deal_grouponcodes'] = array(
        'description' => 'coupon and Events related table',
        'fields' => array(
            'id' => array(
                'description' => t('Primary ID'),
                'type' => 'serial',
                'not null' => TRUE
            ),
            'deal_coupon_id' => array(
                'description' => 'Deal groupon Id from coupon(id)',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'groupon_code' => array(
               'description' => 'Deal groupon Id from coupon(id)',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'is_used' => array(
                'description' => 'Deal name for Groupons.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'created' => array(
                'description' => 'created',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
        ),
        'primary key' => array('id'),
    );

    return $schema;
}

/*
 * Implements hook_uninstall().
 *
 * At uninstall time we'll notify field.module that the entity was deleted
 * so that attached fields can be cleaned up.
 *
 * @ingroup coupon
 */

function coupon_uninstall() {
    
}
