<?php

/**
 * @file
 * Install for a basic Request Quote Form entity - need to create 
 * the base table for RequestQuote entity.
 * This table can have as many columns as you need to keep track of
 * entity-specific data that will not be added via attached fields.
 * 
 */

/**
 * Implements hook_schema().
 */
function cruisesettings_schema() {
  $schema = array();

  // The name of the table can be any name we choose. However, namespacing the
  // table with the module name is best practice.
  $schema['cruisesettings'] = array(
      'description' => 'The base table for requestqutoe.',
      'fields' => array(
          'id' => array(
              'description' => 'Primary key of the requestquiote.',
              'type' => 'serial',
              'unsigned' => TRUE,
              'not null' => TRUE,
          ),
            'stock' => array(
        'description' => 'The Default Cruise Stock for Cruise Events',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
          
      ),
      'primary key' => array('id'),
  );

  return $schema;
}

/*
 * Implements hook_uninstall().
 *
 * At uninstall time we'll notify field.module that the entity was deleted
 * so that attached fields can be cleaned up.
 */

function cruisesettings_uninstall() {
//field_attach_delete_bundle('userdocuments_basic', 'first_example_bundle');
}
