<?php
class MetaTag {
	public $id;
	public $reference_id;
	public $keywords;
	public $author;
        public $title;
	public $description;
	public $http_equiv;
	public $category;
	public $tablename = "metatags";
	
	// Check existence
	public static function checkMetainfoExistence($reference_id, $category) {
		$result = '';
		try {
			$query = db_select ( 'metatags', 'm' );
			$query->fields ( 'm', array (
					'id' 
			) );
			$query->condition ( 'm.reference_id', $reference_id );
			$query->condition ( 'm.category', $category );
			$result = $query->execute ()->fetchField ();
		} catch ( Exception $e ) {
			watchdog ( "Error in selecting metatags table", $e );
		}
		
		return $result;
	}
	
	
	
	
	// Store Metatag information
	public static function storeMetaTags($metaObj) {
		try {
			if ($metaObj->id != '') {
				
				drupal_write_record ( 'metatags', $metaObj, 'id' );
			} else {
				drupal_write_record ( 'metatags', $metaObj );
			}
		} catch ( Exception $e ) {
			watchdog ( "Error (insertion or updation operation) in Metatags Table", $e );
		}
	}
	
	
	
	
	// Get Metatag information by Reference ID (Cruise ID)
	public static function getMetaTagsByID($reference_id, $category) {
		$result = false;
		try {
			$query = db_select ( 'metatags', 'm' );
			$query->fields ( 'm' );
			$query->condition ( 'm.reference_id', $reference_id );
			$query->condition ( 'm.category', $category );
			$result = $query->execute ()->fetchObject ();
		} catch ( Exception $e ) {
			watchdog ( 'metatags', $e );
		}
		return $result;
	}
	
	
	
	
	// Set Meta Tag by Description
	public static function setMetaTagByDescription($reference_id, $category) {
		$metaObj = MetaTag::getMetaTagsByID ( $reference_id, $category );
		
		$description = isset ( $metaObj ) ? $metaObj->description : '';
		
		$meta_description = array (
				'#type' => 'html_tag',
				'#tag' => 'meta',
				'#attributes' => array (
						'name' => 'description',
						'content' => $description 
				) 
		);
		drupal_add_html_head ( $meta_description, 'meta_description' );
	}
	
	
	
	
	// Set Meta Tag by Author
	public static function setMetaTagByAuthor($reference_id) {
	}
	
	
	
	
	// Set Meta Tag by Keywords
	public static function setMetaTagByKeywords($reference_id, $category) {
		$metaObj = MetaTag::getMetaTagsByID ( $reference_id, $category );
		
		$keyWords = isset ( $metaObj ) ? $metaObj->keywords : '';
		$meta_keywords = array (
				'#type' => 'html_tag',
				'#tag' => 'meta',
				'#attributes' => array (
						'name' => 'keywords',
						'content' => $keyWords 
				) 
		);
		drupal_add_html_head ( $meta_keywords, 'meta_keywords' );
	}
        
        
        
        
      public static function setMetaTagByTilte($reference_id, $category) {
        $metaObj = MetaTag::getMetaTagsByID ( $reference_id, $category );
        $metaTitle = isset ( $metaObj ) ? $metaObj->title : '';
        $meta_tile = array(
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => array(
                'name' => 'Tilte',
                'content' => $metaTitle,
            )
        );
        drupal_add_html_head($meta_tile, 'meta_title');
    }

}


