<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function reviewlist_menu() {
    //Admin Management for Request Quote

    $items['reviewsview'] = array(
        'title' => 'Reviewlist',
        'page callback' => 'reviewlist_list_form',
        'access arguments' => array('view review list'),
    );

   

    return $items;
}

/**
 * Implements hook_permission().
 */
function reviewlist_permission() {
    return array(
       
        'view review list' => array(
            'title' => t('View review list'),
        ),
       
       
    );
}


function reviewlist_list_form() {
    global $base_url;
   

  // Check if there is sorting request
  if(isset($_GET['sort']) && isset($_GET['order'])){
    // Sort it Ascending or Descending?
    if($_GET['sort'] == 'asc')
      $sort = 'ASC';
    else
      $sort = 'DESC';
    

// Which column will be sorted
    switch($_GET['order']){
      case 'Name':
        $order = 'name';
        break;
      case 'Type':
        $order = 'type';
        break;
      case 'Category':
        $order = 'categoryname';
        break;
   
      default:
        $order = 'name';
    }
  }
  else{
    // Default sort
    $sort = 'ASC';
    $order = 'title';
  }
  

$output = "";
 
// Select table
  $query = db_select("node", "r");
  $query->join('field_data_field_personname', 'fi', 'r.nid = fi.entity_id');

   $query->join('field_data_field_reviewlink', 'fc', 'r.nid = fc.entity_id');

    $query->fields('r',array('title','nid'));
     $query->fields('fi',array('field_personname_value'));
     $query->fields('fc',array('field_reviewlink_value'));
    $query->condition('type', 'reviews','=');
   
   
   
  // Set order by
  $query->orderBy($order, $sort);
  // Pagination
  $query = $query->extend('TableSort')->extend('PagerDefault')->limit(10);
  

// Execute query
  $result = $query->execute();
  

// Prepare table header
  $header = array(
    array(
      "data" => t('Name'),
      "field" => "title"
    ),
    array(
      "data" => t(' '),
      "field" => "type"
    ),
//    array(
//      "data" => t('Category'),
//      "field" => "categoryname"
//    ),
    array(
      "data" => t('Actions'),
      "field" => "actions"
    ),
//    array(
//      "data" => t('Weight'),
//      "field" => "weight"
//    )
  );
  

$rows = array();
// Looping for filling the table rows
  while($data = $result->fetchObject()){
    // Fill the table rows
    $rows[] = array(
      $data->title,
//      $data->field_vendor_webpage_link_value,
      $data->name,
        '<a href="'. $base_url . '/node/'.$data->nid.'/edit">Edit </a> | <a href="' . $base_url . '/node/'.$data->nid.'/delete">Delete </a>',
     
//      $data->module,
//      $data->weight
    );
  }
  

// Output of table with the paging
  $output = theme_table(
    array(
      "header" => $header,
      "rows" => $rows,
      "attributes" => array("width"=>"100%"),
      "sticky" => true, // Table header will be sticky
      "caption" => "",
      "colgroups" => array(),
      "empty" => t("No records Found") // The message to be displayed if table is empty
    )
  ).theme("pager");
  
  
  $vendorhtml='<a href="'.$base_url.'/node/add/reviews">Add Review</a>';
  $vendorhtml.=$output;
  return $vendorhtml;
}


