<?php

/**
 * Implements hook_menu().
 */
function connectgiftcard_menu() {
  $items = array();
  $items['connectgiftcard'] = array(
      'title' => 'Gift cards',
      'page callback' => 'connect_giftcards',
      'access callback' => 'user_access',
      'access arguments' => array('access content'),
  );
  return $items;
}
function connectgiftcard_theme() {
    $items['connectgiftcard'] = array(
        'template' => 'connectgiftcard',   // here comes your template name
        'render element' => 'content'
    );
    return $items;
}
/**
 * This is the function which is used
 * for creating for creating Product dynamically
 * @param Object $product Description
 * @return type Json boolean Object
 * 
 */
function connect_giftcards() {
    
  try {
    
    global $user;
    //get the product load 
    
       $menulist = getConnectMenu('GIFTCARD');
      $connectresources = array('menu' => $menulist['connectmenu'], 'mobilemenu' => $menulist['mobilemenu']);
        //get the product load 
        return theme('connectgiftcard', $connectresources);
  
    
  } catch (Exception $ex) {
      
    drupal_json_output('The exception ' . $ex);
    
  }
  
}

function template_preprocess_connectgiftcard(&$variables) {
    drupal_add_css(drupal_get_path('module', 'connectgiftcard') . '/css/connectgiftcard.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
}

