<?php

/* 
 * Implementing the hook of home page
 */

function homepagesliders_menu() {
  $items=array();
  
  $items['homepage-sliders'] = array(
		'title' => '',
		'page callback' => 'home_page_add_sliders',
		'file'=>'inc/home_page_sliders.inc',
	       'access arguments' => array('homepages content manage'),
	);
 
  $items['homepage-sliders/view'] = array(
		'title' => '',
		'page callback' => 'home_page_view_list',
		'file'=>'inc/home_page_view.inc',
	     'access arguments' => array('homepages content manage'),
	);
  
  
  $items['homepage-sliders/content'] = array(
		'title' => '',
		'page callback' => 'home_page_content_list',
		'file'=>'inc/home_page_content.inc',
	     'access arguments' => array('homepages content manage'),
	);
  
   $items['homepage-sliders/%/edit'] = array(
		'title' => '',
		'page callback' =>'home_page_slider_edit',
                'page arguments'=>array(1),
		'file'=>'inc/home_page_slider_edit.inc',
	        'access arguments' => array('homepages content manage'),
	);
  
   $items['homepage-sliders/%/delete'] = array(
		'title' => '',
		'page callback' => 'home_page_slider_delete',
                'page arguments'=>array(1),
		'file'=>'inc/home_page_slider_delete.inc',
	       'access arguments' => array('homepages content manage'),
	);
   
   
    return $items;
}


function homepagesliders_permission() {
	return array (
            'homepages content manage'=>array(
                'title' => t ('Home page Content Manage') ,
            ),
		
	);
}


//getting the slider and slider content from this menu and and calling this function in page.tpl.php

function getimagecontent(){
   $gethomeslider= homepagesliders::gethomepagesliderdata();
    $indicators = "";
    $index = 0;
    $sliderlayout="";
    $result="";
    $slidertitel="";
    $sliderbutton="";
  foreach ($gethomeslider as $key => $revalue) {
     $sliderondata=unserialize($revalue->data);
     $slidertitel=empty($sliderondata['Sliderspecialtext'])?"none":"block";
     $sliderbutton=empty($sliderondata['Buttonurl'])?"none":"block";
     $requesturl = empty($sliderondata['links']['secondurl'])?"none":"block";
     $requestdata = empty($sliderondata['links']['secondurl'])?"block":"none";
     $bookdefaulturl = empty($sliderondata['links']['firsturl'])?"none":"block";
     
     $bookdata = empty($sliderondata['links']['firsturl'])?"block":"none";
    $sliderlayout='<div class="slider-caption active" style="'.strtolower($revalue->sliderlayout).': 0%;">
  <div class="row-fluid active" style="display:'.$slidertitel.'">
    <div class="span3 active">
      <div class="welcomeline active"></div>
    </div>
    
    <div class="span6">
      <div class="welcometext active">'.$sliderondata['Sliderspecialtext'].'</div> 
    </div>
    <div class="span3">
      <div class="welcomeline active"></div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12 active">
      <div class="logotext active">
        '.ucwords($sliderondata['Slidertitle']).'
      </div>
    </div>
  </div>
  <div class="row-fluid hidden-phone">
    <div class="span12 active">
      <p>
       '.$sliderondata['Slidercontent']['value'].'
      </p>
    </div>
  </div>
  <div class="row-fluid" style="display:'.$sliderbutton.'">
    <div class="span4 line-padding active">
      <div class="viewbuttonline active"></div>
    </div>
    <div class="span4 hidden-phone">
      <!-- view-featured-button start here -->
      <div class="view-featured-button active">
        <a href="'.$sliderondata['Buttonurl'].'">
          <div class="view-featured-button-inner active">
            '.ucwords($sliderondata['Buttontext']).'
          </div>
        </a>
      </div>
      <!-- view-featured-button end here -->
    </div>
    <div class="span4 line-padding hidden-phone">
      <div class="viewbuttonline active"></div>
    </div>
  </div>
  </div>
  <div class="slider-bottom">
                        <div class="slider-bottomlinks">
                        
                            <div class="book-dining" style="display:'.$bookdefaulturl.'" >
                                <a href="'.$sliderondata['links']['firsturl'].'">
                                    <img src="./sites/all/themes/waterways/assets/img/banner-icon-img.png" style="height:8px;width:29px;"><br>
                                    '.ucwords($sliderondata['links']['firsttext']).'                             </a>
                            </div>
                            
                            <div class="book-dining" style="display:'.$bookdata.'">
                                <a href="/wwccalendar">
                                    <img src="./sites/all/themes/waterways/assets/img/banner-icon-img.png" style="height:8px;width:29px;" ><br>
                                    BOOK A DINING CRUISE
                                </a>
                            </div>
                            
                            <div class="request-proposal" style="display:'.$requesturl.'">
                                <a href="'.$sliderondata['links']['secondurl'].'">
                                    <img src="./sites/all/themes/waterways/assets/img/banner-icon-img.png" style="height:8px;width:29px;"><br>
                                    '.ucwords($sliderondata['links']['secondtext']).'                             </a>
                            </div>
                            
                            <div class="request-proposal" style="display:'.$requestdata.'">
                                <a href="#myModalrequest" role="button" data-toggle="modal">
                                    <img src="./sites/all/themes/waterways/assets/img/banner-icon-img.png" style="height:8px;width:29px;"><br>
                                    REQUEST A PROPOSAL
                                </a>
                            </div>
                           </div>
                    </div>';
      
      //$nosliders=$revalue->image;
      $result.="<div class='item'><img src='" . file_create_url($revalue->image) . "'/><div class='contentSliderController'><div id='sliderContent'>".$sliderlayout."</div></div></div>";
        if ($index == 0) {
                    $indicators.='<li><div class="indicator active" id="ind' . $index . '"></div></li>';
                } else {
                    $indicators.='<li><div class="indicator" id="ind' . $index . '"></div></li>';
                }
                $index++;
            }
  
   return array("items" => $result,"indicators" => $indicators);
}