<?php

/**
 * @file
 * Install for a basic Request Quote Form entity - need to create 
 * the base table for RequestQuote entity.
 * This table can have as many columns as you need to keep track of
 * entity-specific data that will not be added via attached fields.
 * 
 */

/**
 * Implements hook_schema().
 */
function cruiseevents_schema() {
  $schema = array();

  // The name of the table can be any name we choose. However, namespacing the
  // table with the module name is best practice.
  $schema['cruiseevents'] = array(
      'description' => 'The base table for requestqutoe.',
      'fields' => array(
          'id' => array(
              'description' => 'Primary key of the Event Entity Systems.',
              'type' => 'serial',
              'unsigned' => TRUE,
              'not null' => TRUE,
          ),
          'eventStatus' => array(
              'description' => 'The Event Status',//available,unavailable
              'type' => 'varchar',
              'length' => 255,
              'not null' => TRUE,
              'default' => '',
          ),
          'eventName' => array(
              'description' => 'The Event Name',//available,unavailable
              'type' => 'varchar',
              'length' => 255,
              'not null' => TRUE,
              'default' => '',
          ),
          
          
          
          'eventType' => array(
              'description' => 'The type of event ',//seasional/special
              'type' => 'varchar',
              'length' => 255,
              'not null' => TRUE,
              'default' => '',
          ),
          
          
          'recurrenceType' => array(
              'description' => 'The Event Recurrence Type ',//One time,Weekly
              'type' => 'varchar',
              'length' => 255,
              'not null' => TRUE,
              'default' => '',
          ),
          
          
           'eventDays' => array(
              'description' => 'The Selected Event Days',
              'type' => 'varchar',
              'length' => 255,
              'not null' => TRUE,
              'default' => '',
          ),
          
          
          'eventProductitems' => array(
              'description' => 'The Product(Cruise) Event Item Relate Ids',//comma separated values
              'type' => 'varchar',
              'length' => 255,
              'not null' => TRUE,
              'default' => '',
          ),
          
          'eventstartDate' => array(
              'description' => 'The Start Date of the Event',
              'type' => 'int',
              'size' => 'big',
          ),
          
          'eventendDate' => array(
              'description' => 'The End Date of the Event',
              'type' => 'int',
              'size' => 'big',
          ),
          
          
          'created' => array(
              'description' => 'The QuestQuote Created Date and time',
              'type' => 'int',
              'size' => 'big',
          ),
      ),
      'primary key' => array('id'),
  );

  return $schema;
}

/*
 * Implements hook_uninstall().
 *
 * At uninstall time we'll notify field.module that the entity was deleted
 * so that attached fields can be cleaned up.
 */

function cruiseevents_uninstall() {
//field_attach_delete_bundle('userdocuments_basic', 'first_example_bundle');
}
