<?php

/**
 * Implements hook_menu().
 */
function thanksorder_menu() {
  $items = array();
  $items['thanksorder'] = array(
      'title' => 'Thanks Order',
      'page callback' => 'thanks_order',
      'access callback' => 'user_access',
      'access arguments' => array('access content'),
  );
  return $items;
}
function thanksorder_theme() {
    $items['thanksorder'] = array(
        'template' => 'thanksorder',   // here comes your template name
        'render element' => 'content'
    );
    return $items;
}
/**
 * This is the function which is used
 * for creating for creating Product dynamically
 * @param Object $product Description
 * @return type Json boolean Object
 * 
 */
function thanks_order() {
    
  try {
    
    global $user;
    //get the product load 
    return theme('thanksorder');
    
  } catch (Exception $ex) {
      
    drupal_json_output('The exception ' . $ex);
    
  }
  
}

function template_preprocess_thanksorder(&$variables) {
    drupal_add_css(drupal_get_path('module', 'thanksorder') . '/thanksorder.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
}

