<?php

/**
 * Implements hook_menu().
 */
function aboutusaffiliations_menu() {
    $items = array();
    $items['aboutusaffiliations'] = array(
        'title' => 'About Us Affiliations',
        'page callback' => 'aboutus_affiliations',
        'access callback' => 'user_access',
        'access arguments' => array('access content'),
    );
    return $items;
}

function aboutusaffiliations_theme() {
    $items['aboutusaffiliations'] = array(
        'template' => 'aboutusaffiliations', // here comes your template name
        'render element' => 'content'
    );
  
    return $items;
}

/**
 * This is the function which is used
 * for creating for creating Product dynamically
 * @param Object $product Description
 * @return type Json boolean Object
 * 
 */
function aboutus_affiliations() {

    try {


        global $user;

//Affiliation gets load here
        //Loading the About us Overview concepts
     $affliations=  taxonomy_vocabulary_machine_name_load('affiliation');
     $affiliation_elements=taxonomy_get_tree($affliations->vid);
     
      foreach ($affiliation_elements as $element) {
            $affiliationterm=taxonomy_term_load($element->tid);
            $overname=$affiliationterm->name;
            $affiliationtermid=$affiliationterm->tid;
            $boxtitle=  getArrayloop($affiliationterm->field_title);
            
      }
//End of Affiliations gets ends here

        //Get the Overview Content
        //end of getting the Overview Content

        $loadaboutus = getAboutsMenu("Affiliations");
//        $overviewid = 133;
        $templateresources = array(
            'loadmenu' => $loadaboutus['aboutusmenu'],
            'mobilemenu' => $loadaboutus['mobilemenu'],
            'affiliationslogos' => getAffiliattionContent($affiliationtermid, 'field_logo'),
            'affiliationsheroimage' => getAffiliattionContent($affiliationtermid, 'field_heroimage'),
            'affiliationsherocontent' => getAffiliattionContent($affiliationtermid, 'field_sliderboxcontent'),
            'boxtitle'=>$boxtitle
        );



        //get the product load 
        return theme('aboutusaffiliations', $templateresources);
    } catch (Exception $ex) {

        drupal_json_output('The exception ' . $ex);
    }
}

function getAffiliattionContent($tid, $fieldname) {
   
    
    $results = array();
    $sliderHtml = '';
    $sliders = taxonomy_term_load($tid);

    switch ($fieldname) {
        case "field_heroimage":
            foreach ($sliders->$fieldname as $sliderfields) {

                foreach ($sliderfields as $sliderdata) {
                    foreach ($sliderdata as $key => $fieldvalues) {
                        if ($key == 'uri') {
                            $sliderHtml.='<img src="' . file_create_url($fieldvalues) . '"/>';
                        }
                    }
                }
            }
            break;
        case "field_logo":
            foreach ($sliders->$fieldname as $sliderfields) {

                foreach ($sliderfields as $sliderdata) {
                    foreach ($sliderdata as $key => $fieldvalues) {
                        if ($key == 'uri') {
                            $sliderHtml.='<div class="affiliattionLogo"><img src="' . file_create_url($fieldvalues) . '"/></div>';
                        }
                    }
                }
            }

            break;
        case "field_introdescription":
            foreach ($sliders->$fieldname as $sliderfields) {

                foreach ($sliderfields as $sliderdata) {
                    foreach ($sliderdata as $key => $fieldvalues) {
                        if ($key == 'value') {
                            $sliderHtml.=$fieldvalues;
                        }
                    }
                }
            }
            break;
            
            
             case "field_sliderboxcontent":
            foreach ($sliders->$fieldname as $sliderfields) {

                foreach ($sliderfields as $sliderdata) {
                    foreach ($sliderdata as $key => $fieldvalues) {
                        if ($key == 'value') {
                            $sliderHtml.=$fieldvalues;
                        }
                    }
                }
            }
            break;
    }
    return $sliderHtml;
}


function template_preprocess_aboutusaffiliations(&$variables) {
    drupal_add_css(drupal_get_path('module', 'aboutusaffiliations') . '/css/aboutusaffiliations.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
}