<?php

/**
 * Implements hook_menu().
 */
function ticketordercomments_menu() {

    //Ticket Order Comments Table List View
    $items['ticketordercomments'] = array(
        'title' => 'Ticket Order Comments',
        'page callback' => 'ticketordercomments_list_view',
        'access arguments' => array('view ticketordercomments entity'),
    );


    //Manage Ticket Order Comments through Admin Panel
    $items['admin/structure/ticketordercomments/manage'] = array(
        'title' => 'Ticket Order Comments',
        'description' => 'Manage Ticket Order Comments',
        'page callback' => 'ticketordercomments_admin_page',
        'access arguments' => array('administer ticketordercomments entities'),
    );
    return $items;
}

/**
 * Implements hook_permission().
 */
function ticketordercomments_permission() {
    return array(
        'administer ticketordercomments entities' => array(
            'title' => t('Administer ticketordercomments entities'),
            'restrict access' => TRUE,
        ),
        'view ticketordercomments entities' => array(
            'title' => t('View ticketordercomments Entities'),
        ),
    );
}

/**
 * Implements hook_entity_info().
 */
function ticketordercomments_entity_info() {
    $ticketordercomments_info['ticketordercomments'] = array(
        'label' => 'Ticket Order Comments',
        'controller class' => 'TicketOrderCommentsController',
        'base table' => 'ticketordercomments',
        'uri callback' => 'ticketordercomments_uri',
        'fieldable' => TRUE,
        'entity keys' => array(
            'id' => 'id',
        ),
        'static cache' => TRUE,
        'bundles' => array(
            'ticketordercomments_bundle' => array(
                'label' => 'ticketordercomments',
                'admin' => array(
                    'path' => 'admin/structure/ticketordercomments/manage',
                    'access arguments' => array('administer ticketordercomments entities'),
                ),
            ),
        ),
        'view modes' => array(
            'full' => array(
                'label' => t('Full'),
                'custom settings' => FALSE,
            ),
        )
    );
    return $ticketordercomments_info;
}

function ticketordercomments_page_title($ticketordercomments) {
    return 'Ticket Order Comments';
}

function ticketordercomments_load($id = NULL, $reset = FALSE) {
    $ids = (isset($id) ? array($id) : array());
    $ticketordercomments = ticketordercomments_load_multiple($ids, array(), $reset);
    return $ticketordercomments ? reset($ticketordercomments) : FALSE;
}

function ticketordercomments_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
    return entity_load('ticketordercomments', $ids, $conditions, $reset);
}

function ticketordercomments_uri($ticketordercomments) {
    return array(
        'path' => 'ticketordercomments/' . $ticketordercomments->id,
    );
}

function ticketordercomments_admin_page() {
    $output = '';
    $output.=ticketordercomments_list_view();
    return $output;
}

function ticketordercomments_save(&$ticketordercomments) {
    return entity_get_controller('ticketordercomments')->save($ticketordercomments);
}

function ticketordercomments_delete($id) {
    return entity_get_controller('ticketordercomments')->delete($id);
}

function ticketordercomments_list_view() {
    $output = '';
    $header = array(
        array('data' => 'Id', 'field' => 'id'),
        array('data' => 'Order ID', 'field' => 'order_id'),
        array('data' => 'User ID'),
        array('data' => 'User Email'),
        array('data' => 'Receive Email Notifications'),
    );
    if (isset($_GET['sort']) && isset($_GET['order'])) {
        if ($_GET['sort'] == 'asc')
            $sort = 'ASC';
        else
            $sort = 'DESC';

        switch ($_GET['order']) {
            case 'Id':
                $order = 'id';
                break;
            case 'Order ID':
                $order = 'order_id';
                break;
        }
    } else {
        $sort = 'ASC';
        $order = 'id';
    }


    $query = db_select("ticketordercomments", "n");
    $query->fields('n');
    $query->orderBy($order, $sort);
    $query = $query->extend('TableSort')->extend('PagerDefault')->limit(5);
    $result = $query->execute()->fetchAll();

    //var_dump($result[0]->ticket_id);
    //exit();

    global $base_url;
    $rows = array();
    if (count($result) > 0) {
        for ($i = 0; $i < count($result); $i++) {
            $rows[] = array(
                $result[$i]->id,
                $result[$i]->order_id,
                $result[$i]->uid,
                $result[$i]->customer_email,
                $result[$i]->opt_receive_email_notification,
            );
        }
    }

    $output .= '<div class="">';
    $output .= '<div class="">';

    $output .= '</div>';
    $output .= theme_table(
                    array(
                        'header' => $header,
                        'rows' => $rows,
                        'attributes' => array('class' => array('')),
                        'sticky' => true,
                        'caption' => '',
                        'colgroups' => array(),
                        'empty' => t("No Records!"),
                    )
            ) . theme('pager');

    $output .= '</div>';

    return $output;
}
