
<?php

/**
 * Implements hook_schema().
 */
function ticketordercomments_schema() {
    $schema = array();

    $schema['ticketordercomments'] = array(
        'description' => 'The base table for ticketordercomments.',
        'fields' => array(
            'id' => array(
                'description' => 'Primary key.',
                'type' => 'serial',
                'unsigned' => TRUE,
                'not null' => TRUE,
            ),
            'order_id' => array(
                'description' => 'Ubercart Order ID',
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => 0,
            ),
            'uid' => array(
                'description' => 'User ID',
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => 0,
            ),
            'opt_celebration_comments' => array(
                'type' => 'text',
                'size' => 'big',
                'not null' => TRUE
            ),
            'opt_receive_email_notification' => array(
                'description' => 'opt_receive_email_notification',
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => 0,
            ),
            'customer_email' => array(
                'description' => 'Customer Email',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'opt_limited_mobility' => array(
                'description' => 'opt_limited_mobility',
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => 0,
            ),
            'opt_food_allergy' => array(
                'description' => 'opt_food_allergy',
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => 0,
            ),
            'opt_another_party' => array(
                'description' => 'opt_another_party',
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => 0,
            ),
            'opt_another_party_comments' => array(
                'type' => 'text',
                'size' => 'big',
                'not null' => TRUE
            ),
            'opt_celebration' => array(
                'description' => 'opt_celebration',
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => 0,
            ),
            'what_they_brought' => array(
                'description' => 'what_they_brought',
                'type' => 'text',
                'size' => 'big',
                'not null' => TRUE
            ),
            'order_total' => array(
                'description' => 'The total amount to be paid for the order.',
                'type' => 'numeric',
                'precision' => 16,
                'scale' => 5,
                'not null' => TRUE,
                'default' => 0.0,
            ),
        ),
        'primary key' => array('id'),
    );




    return $schema;
}

