<?php

/**
 * Implements hook_menu().
 */
function aboutusourcrew_menu() {
    $items = array();
    $items['crewview'] = array(
        'title' => 'About Us Our Crew',
        'page callback' => 'aboutus_ourcrew',
        'access callback' => 'user_access',
        'access arguments' => array('access content'),
    );
    $items['crewmember/id/%'] = array(
        'title' => 'About Us Our Crew',
        'page callback' => 'crewmember',
//        'access callback' => 'user_access',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
    );
    return $items;
}

function aboutusourcrew_theme() {
    $items['aboutusourcrew'] = array(
        'template' => 'aboutusourcrew', // here comes your template name
        'render element' => 'content'
    );
    $items['crewmember'] = array(
        'template' => 'crewmember', // here comes your template name
        'render element' => 'content'
    );
    return $items;
}

/**
 * This is the function which is used
 * for creating for creating Product dynamically
 * @param Object $product Description
 * @return type Json boolean Object
 * 
 */
function aboutus_ourcrew() {
     
    try {


       
     
        
        
        
        //
        
        
        
        
        
        
        
  
      
$aboutuscrew=  taxonomy_vocabulary_machine_name_load('aboutuscrew');

     $crew_elements=taxonomy_get_tree($aboutuscrew->vid);
     
      foreach ($crew_elements as $element) {
            $crewterm=taxonomy_term_load($element->tid);
            $crewtermname=$crewterm->name;
           $title=getArrayloop($crewterm->field_title);
          
            $topsliders=getSliders($crewterm->tid, 'field_slider_image');

            $sliderbox1content1=getArrayloop($crewterm->field_sliderboxcontent);
           
         
      }

        //Get the Overview Content crewmembers 
        //end of getting the Overview Content

        $loadaboutus = getAboutsMenu("Our Crew");
        $overviewid = 131;
        $templateresources = array(
            'loadmenu' => $loadaboutus['aboutusmenu'],
            'mobilemenu' => $loadaboutus['mobilemenu'],
            'crewmembers' => getCrewMembers(),
            'crewheroimage' => $topsliders,//getCrewfieldContent($overviewid, 'field_heroimage'),
            'crewherocontent' => $sliderbox1content1,//getCrewfieldContent($overviewid, 'field_introdescription')
            'boxtitle'=>$title
            
            );



        //get the product load 
        return theme('aboutusourcrew', $templateresources);
    } catch (Exception $ex) {

        drupal_json_output('The exception ' . $ex);
    }
}

/**
 * This is the function which is used
 * for creating for creating Product dynamically
 * @param Object $product Description
 * @return type Json boolean Object
 * 
 */


function crewmember($tid) {
	
    try {
        
        
        $templateresources = array(
        'crewname' => getCrewfieldContent($tid, 'name'),
        'titleone'=>getCrewfieldContent($tid, 'field_title'),
        'titletwo'=>getCrewfieldContent($tid, 'field_title2'),
        		
//        'crewheroimage' => getCrewfieldContent($overviewid, 'field_heroimage'),
             'crewheroimage'=>getSliders($tid, 'field_slider_image'),
        'crewherocontent' => getCrewfieldContent($tid, 'field_sliderboxcontent'),
        'biographyslidercontent' => getCrewfieldContent($tid, 'field_middle_content'),
//        'biographysliders' => getSliders($tid, 'field_slider_image')
             'biographysliders' => getCrewfieldContent($tid, 'field_middle_slider_img')
        );
        
        
       
        
        
        
        
        return theme('crewmember', $templateresources);
    } catch (Exception $ex) {

        drupal_json_output('The exception ' . $ex);
    }
}

function getCrewfieldContent($tid, $fieldname) {

    $results = array();
    $sliderHtml = '';
    $sliders = taxonomy_term_load($tid);
    
   
    switch ($fieldname) {
        case "name":
            $sliderHtml.=$sliders->name;
            break;
        case "field_heroimage":
            foreach ($sliders->$fieldname as $sliderfields) {

                foreach ($sliderfields as $sliderdata) {
                    foreach ($sliderdata as $key => $fieldvalues) {
                        if ($key == 'uri') {
                            $sliderHtml.='<div class="item"><img src="' . file_create_url($fieldvalues) . '"/></div>';
                        }
                    }
                }
            }
            break;
            
            //Crewmember slider second slider template image
            
            
             case "field_middle_slider_img":
            foreach ($sliders->$fieldname as $sliderfields) {

                foreach ($sliderfields as $sliderdata) {
                    foreach ($sliderdata as $key => $fieldvalues) {
                        if ($key == 'uri') {
                            $sliderHtml.='<div class="item"><img src="' . file_create_url($fieldvalues) . '"/></div>';
                        }
                    }
                }
            }
            break;
            
            
        case "field_sliderboxcontent":
            foreach ($sliders->$fieldname as $sliderfields) {

                foreach ($sliderfields as $sliderdata) {
                    foreach ($sliderdata as $key => $fieldvalues) {
                        if ($key == 'value') {
                            $sliderHtml.=$fieldvalues;
                        }
                    }
                }
            }

            break;
            //middle content for crew member template
//            
             case "field_middle_content":
            foreach ($sliders->$fieldname as $sliderfields) {

                foreach ($sliderfields as $sliderdata) {
                    foreach ($sliderdata as $key => $fieldvalues) {
                        if ($key == 'value') {
                            $sliderHtml.=$fieldvalues;
                        }
                    }
                }
            }

            break;
        case "field_introdescription":
            foreach ($sliders->$fieldname as $sliderfields) {

                foreach ($sliderfields as $sliderdata) {
                    foreach ($sliderdata as $key => $fieldvalues) {
                        if ($key == 'value') {
                            $sliderHtml.=$fieldvalues;
                        }
                    }
                }
            }
            break;
            
         case "field_title":
           	foreach ($sliders->$fieldname as $key => $values) {
           		if(isset($values[0]['value'])){
           			$sliderHtml=$values[0]['value'];
           		}
           	}
            	break;
            	
         case "field_title2":
           	foreach ($sliders->$fieldname as $key => $values) {
           		if(isset($values[0]['value'])){
           			$sliderHtml=$values[0]['value'];
           		}
           	}
            	break;
    }
    return $sliderHtml;
}


//Loading Crew Members Template 
function getCrewMembers() {
    
     $crewmembershtml='';
   $crewtemplates=  taxonomy_vocabulary_machine_name_load('cremmembertemplate');
//
     $crew_member_elements=taxonomy_get_tree($crewtemplates->vid);
//     
      foreach ($crew_member_elements as $member_element) {
          //load the taxonomy term
          $crew_member_term_template=  taxonomy_term_load($member_element->tid);
        
          
          $url=url('taxonomy/term/' . $member_element->tid);
          $crew_member_template_name=$crew_member_term_template->name;
          $crewmem_template_background=file_create_url(getArrayloop($crew_member_term_template->field_crewimage));
          $crew_member_short_description=getArrayloop($crew_member_term_template->field_over_short_description);
          
          
          
          $crewmembershtml.='<li><div class="sliderBox"><div class="sliderBoxout" style="background-image: url('.$crewmem_template_background.'); width: 250px; height:250px;"><div class="event-bgimage"></div><div class="sliderBoxInner">' . $crew_member_template_name . '</div></div><div class="sliderBoxover" onclick="crewMemberDetails('.$crew_member_term_template->tid.')" style="display: none;"><div class="sliderBox-first-inner"><img src="' . base_path() . 'sites/all/themes/waterways/assets/img/innerbox-top-img.png"><br>'.$crew_member_short_description.'<br>
                     <a>Click to Learn More</a><div class="line"></div></div></div></div></li>';
          
          
          
      }
    return $crewmembershtml;
}

//End of Loading CrewMember Templates



function getCrewMembers1($tid) {
    $children = taxonomy_get_children($tid);
    $crewmembershtml = '';  
    foreach ($children as $key => $values) {
        $childrens = taxonomy_get_children($key);
        foreach ($childrens as $keys => $values) {
            $crewMembers = taxonomy_term_load($keys);
            $crewdata = renderCrewMembers($crewMembers);
            $crewimgurl='';
            if(isset($crewdata['field_crewimage']) && $crewdata['field_crewimage'] !=''){
                $crewimgurl=  file_create_url($crewdata['field_crewimage']);
            }
            
//            $crewmembershtml.='<li><div class="sliderBox"><div class="sliderBoxout" style="background-image: url('.base_path().'sites/default/files/weddingpackages.png); width: 250px; height:250px;"><div class="event-bgimage"></div><div class="sliderBoxInner">' . $crewdata['name'] . '</div></div><div class="sliderBoxover" onclick="crewMemberDetails('.$crewdata['tid'].')" style="display: none;"><div class="sliderBox-first-inner"><img src="' . base_path() . 'sites/all/themes/waterways/assets/img/innerbox-top-img.png"><br>Beard in lo-fi, raw denim ea fugiat organic consectetur. Gentrify duis proident.<br>
//                     <a>Click to Learn More</a><div class="line"></div></div></div></div></li>';
            $crewmembershtml.='<li><div class="sliderBox"><div class="sliderBoxout" style="background-image: url('.$crewimgurl.'); width: 250px; height:250px;"><div class="event-bgimage"></div><div class="sliderBoxInner">' . $crewdata['name'] . '</div></div><div class="sliderBoxover" onclick="crewMemberDetails('.$crewdata['tid'].')" style="display: none;"><div class="sliderBox-first-inner"><img src="' . base_path() . 'sites/all/themes/waterways/assets/img/innerbox-top-img.png"><br>Beard in lo-fi, raw denim ea fugiat organic consectetur. Gentrify duis proident.<br>
                     <a>Click to Learn More</a><div class="line"></div></div></div></div></li>';
        }
    }
    return $crewmembershtml;
}

function renderCrewMembers($crewMembers) {
    $crewdata = '';
    foreach ($crewMembers as $key => $values) {

        if (is_array($values)) {

            $crewdata[$key] = getArrayloop($values);
        } else {
            $crewdata[$key] = $values;
        }
    }
    return $crewdata;
}

function template_preprocess_aboutusourcrew(&$variables) {
    drupal_add_css(drupal_get_path('module', 'aboutusourcrew') . '/css/aboutusourcrew.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
}

function template_preprocess_crewmember(&$variables) {
    drupal_add_css(drupal_get_path('module', 'aboutusourcrew') . '/css/aboutusourcrew.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
}

