<?php


/**
 * @file
* Install for a basic Request Quote Form entity - need to create
* the base table for discountcodes entity.
* This table can have as many columns as you need to keep track of
* entity-specific data that will not be added via attached fields.
*
*/

/**
 * Implements hook_schema().
*/
function discountcodes_schema() {
	$schema = array();

	// The name of the table can be any name we choose. However, namespacing the
	// table with the module name is best practice.
	$schema['discountcodes'] = array(
			'description' => 'The base table for requestqutoe.',
			'fields' => array(
					'id' => array(
							'description' => 'Primary key of the requestquiote.',
							'type' => 'serial',
							'unsigned' => TRUE,
							'not null' => TRUE,
					),
					
					
					'title' => array(
							'description' => 'The Promo code title',
							'type' => 'varchar',
							'length' => 255,
							'not null' => TRUE,
							'default' => '',
					),
					
					'code' => array(
							'description' => 'The Promo code value',
							'type' => 'varchar',
							'length' => 255,
							'not null' => TRUE,
							'default' => '',
					),
						

					'rate' => array(
							'description' => 'The rate value specified for the prmo value.',
							'type' => 'numeric',
							'precision' => 16,
							'scale' => 5,
							'not null' => TRUE,
							'default' => 0.0,
					),
		
					//1 for percentage,,2 for flatrate,3 for 2 or 1
					'type' => array(
					'description' => 'The rate type .',
					'type' => 'int',
					'unsigned' => TRUE,
					'not null' => TRUE,
					'default' => 0,
					),

					'validfrom' => array (
							'description' => 'The discount code valid start date .',
							'type' => 'int',
							'not null' => TRUE,
							'default' => 0
					),
				
					'validuntil' => array (
							'description' => 'The discount code valid until date .',
							'type' => 'int',
							'not null' => TRUE,
							'default' => 0
					),

					//0 for inactive 1 for active
					'active' => array (
							'description' => 'The discount code Active status .',
							'type' => 'int',
							'not null' => TRUE,
							'default' => 0
					),
					 
					'created' => array(
					'description' => 'The QuestQuote Created Date and time',
					'type' => 'varchar',
					'length' => 255,
					'not null' => TRUE,
					'default' => '',
					),
			),
			'primary key' => array('id'),
	);
	
	// discount codes used by events
	$schema ['events_discount_codes'] = array (
			'description' => 'Cruise Discount codes assigned for cruise templates',
			'fields' => array (
					'id' => array (
							'description' => 'Primary key.',
							'type' => 'serial',
							'unsigned' => TRUE,
							'not null' => TRUE
					),
					'cid' => array (
							'type' => 'int',
							'unsigned' => TRUE,
							'not null' => TRUE,
							'default' => 0
					),
					
					
					'template_id' => array (
							'type' => 'int',
							'unsigned' => TRUE,
							'not null' => TRUE,
							'default' => 0
					),
					
					'event_id' => array (
							'type' => 'int',
							'unsigned' => TRUE,
							'not null' => TRUE,
							'default' => 0
					),
					
					'order_id' => array (
							'type' => 'int',
							'unsigned' => TRUE,
							'not null' => TRUE,
							'default' => 0
					),
					
			),
			'primary key' => array (
					'id'
			)
	);
	
	
	// cruise template assigned discount codes
	$schema ['cruise_discount_codes'] = array (
			'description' => 'Cruise Discount codes assigned for cruise templates',
			'fields' => array (
					'id' => array (
							'description' => 'Primary key.',
							'type' => 'serial',
							'unsigned' => TRUE,
							'not null' => TRUE
					),
					'cid' => array (
							'type' => 'int',
							'unsigned' => TRUE,
							'not null' => TRUE,
							'default' => 0
					),
						
						
					'template_id' => array (
							'type' => 'int',
							'unsigned' => TRUE,
							'not null' => TRUE,
							'default' => 0
					),
						
					//0 for inactive 1 for active
					'active' => array (
							'description' => 'The discount code Active status .',
							'type' => 'int',
							'not null' => TRUE,
							'default' => 0
					),
					 
						
			),
			'primary key' => array (
					'id'
			)
	);

	return $schema;
}

/*
 * Implements hook_uninstall().
*
* At uninstall time we'll notify field.module that the entity was deleted
* so that attached fields can be cleaned up.
*/

function discountcodes_uninstall() {
	//field_attach_delete_bundle('userdocuments_basic', 'first_example_bundle');
}
