
<?php

/**
 * Implements hook_schema().
 */
function cruisecategory_schema() {
	$schema = array ();
	
	$schema ['cruisecategory'] = array (
			'description' => 'The base table for cruisecategory.',
			'fields' => array (
					'cruise_category_id' => array (
							'description' => 'Primary key.',
							'type' => 'serial',
							'unsigned' => TRUE,
							'not null' => TRUE 
					),
					'cruise_category_name' => array (
							'description' => 'Cruise Category Name',
							'type' => 'varchar',
							'length' => 255,
							'not null' => TRUE,
							'default' => '' 
					),
					
					
			),
			'primary key' => array (
					'cruise_category_id' 
			) 
	);
	
	return $schema;
}

